import 'dart:ui';

const APPBAR_COLOR = Color(0xFFFFA45F);
const MY_COLOR= Color(0xFF4DBAC2);
const BOTTOMNAVIGATION_COLOR= Color(0xFFFFFFFF);
const BODY_TEXT_COLOR= Color(0xFFE479F5);
const INPUT_BG_COLOR = Color(0xFF99D750);