// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDCEYhd8qIv5xCKTpWpobXVqMdqzCvIVU',
    appId: '1:637519283420:web:49f1eeee42b82a879a2019',
    messagingSenderId: '637519283420',
    projectId: 'snp-system',
    authDomain: 'snp-system.firebaseapp.com',
    storageBucket: 'snp-system.appspot.com',
    measurementId: 'G-PPJGBBS745',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8lM8QJQ-wCOfEbit2t2pMPDXqPgna-04',
    appId: '1:637519283420:android:274790cfc07fada39a2019',
    messagingSenderId: '637519283420',
    projectId: 'snp-system',
    storageBucket: 'snp-system.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkwPOOeO4GssPIUoBws6TsR93dQSjIjkQ',
    appId: '1:637519283420:ios:e70f6a540915283c9a2019',
    messagingSenderId: '637519283420',
    projectId: 'snp-system',
    storageBucket: 'snp-system.appspot.com',
    iosClientId: '637519283420-kao092uiia69ji3hthj1glsak0ijv27j.apps.googleusercontent.com',
    iosBundleId: 'com.example.golfBooking',
  );
}
